//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATS.RChilliParserHelper.CVXtractor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="CVXtractorService", ConfigurationName="CVXtractor.CVXtractor_PortType")]
    public interface CVXtractor_PortType {
        
        // CODEGEN: Generating message contract since the operation ProcessCV is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="CVXtractorService#ProcessCV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ATS.RChilliParserHelper.CVXtractor.ProcessCV_Out ProcessCV(ATS.RChilliParserHelper.CVXtractor.ProcessCV_In request);
        
        // CODEGEN: Generating message contract since the operation ProcessJobOrder is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="CVXtractorService#ProcessJobOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ATS.RChilliParserHelper.CVXtractor.ProcessJobOrder_Out ProcessJobOrder(ATS.RChilliParserHelper.CVXtractor.ProcessJobOrder_In request);
        
        // CODEGEN: Generating message contract since the operation ConvertCV is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="CVXtractorService#ConvertCV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ATS.RChilliParserHelper.CVXtractor.ConvertCV_Out ConvertCV(ATS.RChilliParserHelper.CVXtractor.ConvertCV_In request);
        
        // CODEGEN: Generating message contract since the operation ReformatCV is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="CVXtractorService#ReformatCV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ATS.RChilliParserHelper.CVXtractor.ReformatCV_Out ReformatCV(ATS.RChilliParserHelper.CVXtractor.ReformatCV_In request);
        
        // CODEGEN: Generating message contract since the operation PDF2Word is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="CVXtractorService#PDF2Word", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ATS.RChilliParserHelper.CVXtractor.PDF2Word_Out PDF2Word(ATS.RChilliParserHelper.CVXtractor.PDF2Word_In request);
        
        // CODEGEN: Generating message contract since the operation ProcessBatch is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="CVXtractorService#ProcessBatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ATS.RChilliParserHelper.CVXtractor.ProcessBatch_Out ProcessBatch(ATS.RChilliParserHelper.CVXtractor.ProcessBatch_In request);
        
        // CODEGEN: Generating message contract since the operation InstallLists is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="CVXtractorService#InstallLists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ATS.RChilliParserHelper.CVXtractor.InstallLists_Out InstallLists(ATS.RChilliParserHelper.CVXtractor.InstallLists_In request);
        
        // CODEGEN: Generating message contract since the operation RetrieveLists is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="CVXtractorService#RetrieveLists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ATS.RChilliParserHelper.CVXtractor.RetrieveLists_Out RetrieveLists(ATS.RChilliParserHelper.CVXtractor.RetrieveLists_In request);
        
        // CODEGEN: Generating message contract since the operation CreateAccount is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="CVXtractorService#CreateAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ATS.RChilliParserHelper.CVXtractor.CreateAccount_Out CreateAccount(ATS.RChilliParserHelper.CVXtractor.CreateAccount_In request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class ProcessCV : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] document_urlField;
        
        private string accountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] document_url {
            get {
                return this.document_urlField;
            }
            set {
                this.document_urlField = value;
                this.RaisePropertyChanged("document_url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("account");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class ProcessCVResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hrxmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string hrxml {
            get {
                return this.hrxmlField;
            }
            set {
                this.hrxmlField = value;
                this.RaisePropertyChanged("hrxml");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessCV_In {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.ProcessCV ProcessCV;
        
        public ProcessCV_In() {
        }
        
        public ProcessCV_In(ATS.RChilliParserHelper.CVXtractor.ProcessCV ProcessCV) {
            this.ProcessCV = ProcessCV;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessCV_Out {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.ProcessCVResponse ProcessCVResponse;
        
        public ProcessCV_Out() {
        }
        
        public ProcessCV_Out(ATS.RChilliParserHelper.CVXtractor.ProcessCVResponse ProcessCVResponse) {
            this.ProcessCVResponse = ProcessCVResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class ProcessJobOrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] document_urlField;
        
        private string accountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] document_url {
            get {
                return this.document_urlField;
            }
            set {
                this.document_urlField = value;
                this.RaisePropertyChanged("document_url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("account");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class ProcessJobOrderResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vacxmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string vacxml {
            get {
                return this.vacxmlField;
            }
            set {
                this.vacxmlField = value;
                this.RaisePropertyChanged("vacxml");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessJobOrder_In {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.ProcessJobOrder ProcessJobOrder;
        
        public ProcessJobOrder_In() {
        }
        
        public ProcessJobOrder_In(ATS.RChilliParserHelper.CVXtractor.ProcessJobOrder ProcessJobOrder) {
            this.ProcessJobOrder = ProcessJobOrder;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessJobOrder_Out {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.ProcessJobOrderResponse ProcessJobOrderResponse;
        
        public ProcessJobOrder_Out() {
        }
        
        public ProcessJobOrder_Out(ATS.RChilliParserHelper.CVXtractor.ProcessJobOrderResponse ProcessJobOrderResponse) {
            this.ProcessJobOrderResponse = ProcessJobOrderResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class ConvertCV : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] document_urlField;
        
        private string accountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] document_url {
            get {
                return this.document_urlField;
            }
            set {
                this.document_urlField = value;
                this.RaisePropertyChanged("document_url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("account");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class ConvertCVResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string convertField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string convert {
            get {
                return this.convertField;
            }
            set {
                this.convertField = value;
                this.RaisePropertyChanged("convert");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertCV_In {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.ConvertCV ConvertCV;
        
        public ConvertCV_In() {
        }
        
        public ConvertCV_In(ATS.RChilliParserHelper.CVXtractor.ConvertCV ConvertCV) {
            this.ConvertCV = ConvertCV;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertCV_Out {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.ConvertCVResponse ConvertCVResponse;
        
        public ConvertCV_Out() {
        }
        
        public ConvertCV_Out(ATS.RChilliParserHelper.CVXtractor.ConvertCVResponse ConvertCVResponse) {
            this.ConvertCVResponse = ConvertCVResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class ReformatCV : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] document_urlField;
        
        private string accountField;
        
        private string templateField;
        
        private string hrxmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] document_url {
            get {
                return this.document_urlField;
            }
            set {
                this.document_urlField = value;
                this.RaisePropertyChanged("document_url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
                this.RaisePropertyChanged("template");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string hrxml {
            get {
                return this.hrxmlField;
            }
            set {
                this.hrxmlField = value;
                this.RaisePropertyChanged("hrxml");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class ReformatCVResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] docField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] doc {
            get {
                return this.docField;
            }
            set {
                this.docField = value;
                this.RaisePropertyChanged("doc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReformatCV_In {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.ReformatCV ReformatCV;
        
        public ReformatCV_In() {
        }
        
        public ReformatCV_In(ATS.RChilliParserHelper.CVXtractor.ReformatCV ReformatCV) {
            this.ReformatCV = ReformatCV;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReformatCV_Out {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.ReformatCVResponse ReformatCVResponse;
        
        public ReformatCV_Out() {
        }
        
        public ReformatCV_Out(ATS.RChilliParserHelper.CVXtractor.ReformatCVResponse ReformatCVResponse) {
            this.ReformatCVResponse = ReformatCVResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class PDF2Word : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] document_urlField;
        
        private string accountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] document_url {
            get {
                return this.document_urlField;
            }
            set {
                this.document_urlField = value;
                this.RaisePropertyChanged("document_url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("account");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class PDF2WordResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] docField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] doc {
            get {
                return this.docField;
            }
            set {
                this.docField = value;
                this.RaisePropertyChanged("doc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PDF2Word_In {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.PDF2Word PDF2Word;
        
        public PDF2Word_In() {
        }
        
        public PDF2Word_In(ATS.RChilliParserHelper.CVXtractor.PDF2Word PDF2Word) {
            this.PDF2Word = PDF2Word;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PDF2Word_Out {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.PDF2WordResponse PDF2WordResponse;
        
        public PDF2Word_Out() {
        }
        
        public PDF2Word_Out(ATS.RChilliParserHelper.CVXtractor.PDF2WordResponse PDF2WordResponse) {
            this.PDF2WordResponse = PDF2WordResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class ProcessBatch : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] document_urlField;
        
        private string accountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] document_url {
            get {
                return this.document_urlField;
            }
            set {
                this.document_urlField = value;
                this.RaisePropertyChanged("document_url");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("account");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class ProcessBatchResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessBatch_In {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.ProcessBatch ProcessBatch;
        
        public ProcessBatch_In() {
        }
        
        public ProcessBatch_In(ATS.RChilliParserHelper.CVXtractor.ProcessBatch ProcessBatch) {
            this.ProcessBatch = ProcessBatch;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessBatch_Out {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.ProcessBatchResponse ProcessBatchResponse;
        
        public ProcessBatch_Out() {
        }
        
        public ProcessBatch_Out(ATS.RChilliParserHelper.CVXtractor.ProcessBatchResponse ProcessBatchResponse) {
            this.ProcessBatchResponse = ProcessBatchResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class InstallLists : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string list_typeField;
        
        private string accountField;
        
        private string list_contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string list_type {
            get {
                return this.list_typeField;
            }
            set {
                this.list_typeField = value;
                this.RaisePropertyChanged("list_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string list_content {
            get {
                return this.list_contentField;
            }
            set {
                this.list_contentField = value;
                this.RaisePropertyChanged("list_content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class InstallListsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string return_messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string return_message {
            get {
                return this.return_messageField;
            }
            set {
                this.return_messageField = value;
                this.RaisePropertyChanged("return_message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InstallLists_In {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.InstallLists InstallLists;
        
        public InstallLists_In() {
        }
        
        public InstallLists_In(ATS.RChilliParserHelper.CVXtractor.InstallLists InstallLists) {
            this.InstallLists = InstallLists;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InstallLists_Out {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.InstallListsResponse InstallListsResponse;
        
        public InstallLists_Out() {
        }
        
        public InstallLists_Out(ATS.RChilliParserHelper.CVXtractor.InstallListsResponse InstallListsResponse) {
            this.InstallListsResponse = InstallListsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class RetrieveLists : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string list_typeField;
        
        private string accountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string list_type {
            get {
                return this.list_typeField;
            }
            set {
                this.list_typeField = value;
                this.RaisePropertyChanged("list_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("account");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class RetrieveListsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string list_contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string list_content {
            get {
                return this.list_contentField;
            }
            set {
                this.list_contentField = value;
                this.RaisePropertyChanged("list_content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveLists_In {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.RetrieveLists RetrieveLists;
        
        public RetrieveLists_In() {
        }
        
        public RetrieveLists_In(ATS.RChilliParserHelper.CVXtractor.RetrieveLists RetrieveLists) {
            this.RetrieveLists = RetrieveLists;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveLists_Out {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.RetrieveListsResponse RetrieveListsResponse;
        
        public RetrieveLists_Out() {
        }
        
        public RetrieveLists_Out(ATS.RChilliParserHelper.CVXtractor.RetrieveListsResponse RetrieveListsResponse) {
            this.RetrieveListsResponse = RetrieveListsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class CreateAccount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountField;
        
        private string credentialsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string credentials {
            get {
                return this.credentialsField;
            }
            set {
                this.credentialsField = value;
                this.RaisePropertyChanged("credentials");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="CVXtractorService")]
    public partial class CreateAccountResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string return_messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string return_message {
            get {
                return this.return_messageField;
            }
            set {
                this.return_messageField = value;
                this.RaisePropertyChanged("return_message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccount_In {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.CreateAccount CreateAccount;
        
        public CreateAccount_In() {
        }
        
        public CreateAccount_In(ATS.RChilliParserHelper.CVXtractor.CreateAccount CreateAccount) {
            this.CreateAccount = CreateAccount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccount_Out {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="CVXtractorService", Order=0)]
        public ATS.RChilliParserHelper.CVXtractor.CreateAccountResponse CreateAccountResponse;
        
        public CreateAccount_Out() {
        }
        
        public CreateAccount_Out(ATS.RChilliParserHelper.CVXtractor.CreateAccountResponse CreateAccountResponse) {
            this.CreateAccountResponse = CreateAccountResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CVXtractor_PortTypeChannel : ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CVXtractor_PortTypeClient : System.ServiceModel.ClientBase<ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType>, ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType {
        
        public CVXtractor_PortTypeClient() {
        }
        
        public CVXtractor_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CVXtractor_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CVXtractor_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CVXtractor_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATS.RChilliParserHelper.CVXtractor.ProcessCV_Out ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType.ProcessCV(ATS.RChilliParserHelper.CVXtractor.ProcessCV_In request) {
            return base.Channel.ProcessCV(request);
        }
        
        public ATS.RChilliParserHelper.CVXtractor.ProcessCVResponse ProcessCV(ATS.RChilliParserHelper.CVXtractor.ProcessCV ProcessCV1) {
            ATS.RChilliParserHelper.CVXtractor.ProcessCV_In inValue = new ATS.RChilliParserHelper.CVXtractor.ProcessCV_In();
            inValue.ProcessCV = ProcessCV1;
            ATS.RChilliParserHelper.CVXtractor.ProcessCV_Out retVal = ((ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType)(this)).ProcessCV(inValue);
            return retVal.ProcessCVResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATS.RChilliParserHelper.CVXtractor.ProcessJobOrder_Out ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType.ProcessJobOrder(ATS.RChilliParserHelper.CVXtractor.ProcessJobOrder_In request) {
            return base.Channel.ProcessJobOrder(request);
        }
        
        public ATS.RChilliParserHelper.CVXtractor.ProcessJobOrderResponse ProcessJobOrder(ATS.RChilliParserHelper.CVXtractor.ProcessJobOrder ProcessJobOrder1) {
            ATS.RChilliParserHelper.CVXtractor.ProcessJobOrder_In inValue = new ATS.RChilliParserHelper.CVXtractor.ProcessJobOrder_In();
            inValue.ProcessJobOrder = ProcessJobOrder1;
            ATS.RChilliParserHelper.CVXtractor.ProcessJobOrder_Out retVal = ((ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType)(this)).ProcessJobOrder(inValue);
            return retVal.ProcessJobOrderResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATS.RChilliParserHelper.CVXtractor.ConvertCV_Out ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType.ConvertCV(ATS.RChilliParserHelper.CVXtractor.ConvertCV_In request) {
            return base.Channel.ConvertCV(request);
        }
        
        public ATS.RChilliParserHelper.CVXtractor.ConvertCVResponse ConvertCV(ATS.RChilliParserHelper.CVXtractor.ConvertCV ConvertCV1) {
            ATS.RChilliParserHelper.CVXtractor.ConvertCV_In inValue = new ATS.RChilliParserHelper.CVXtractor.ConvertCV_In();
            inValue.ConvertCV = ConvertCV1;
            ATS.RChilliParserHelper.CVXtractor.ConvertCV_Out retVal = ((ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType)(this)).ConvertCV(inValue);
            return retVal.ConvertCVResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATS.RChilliParserHelper.CVXtractor.ReformatCV_Out ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType.ReformatCV(ATS.RChilliParserHelper.CVXtractor.ReformatCV_In request) {
            return base.Channel.ReformatCV(request);
        }
        
        public ATS.RChilliParserHelper.CVXtractor.ReformatCVResponse ReformatCV(ATS.RChilliParserHelper.CVXtractor.ReformatCV ReformatCV1) {
            ATS.RChilliParserHelper.CVXtractor.ReformatCV_In inValue = new ATS.RChilliParserHelper.CVXtractor.ReformatCV_In();
            inValue.ReformatCV = ReformatCV1;
            ATS.RChilliParserHelper.CVXtractor.ReformatCV_Out retVal = ((ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType)(this)).ReformatCV(inValue);
            return retVal.ReformatCVResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATS.RChilliParserHelper.CVXtractor.PDF2Word_Out ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType.PDF2Word(ATS.RChilliParserHelper.CVXtractor.PDF2Word_In request) {
            return base.Channel.PDF2Word(request);
        }
        
        public ATS.RChilliParserHelper.CVXtractor.PDF2WordResponse PDF2Word(ATS.RChilliParserHelper.CVXtractor.PDF2Word PDF2Word1) {
            ATS.RChilliParserHelper.CVXtractor.PDF2Word_In inValue = new ATS.RChilliParserHelper.CVXtractor.PDF2Word_In();
            inValue.PDF2Word = PDF2Word1;
            ATS.RChilliParserHelper.CVXtractor.PDF2Word_Out retVal = ((ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType)(this)).PDF2Word(inValue);
            return retVal.PDF2WordResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATS.RChilliParserHelper.CVXtractor.ProcessBatch_Out ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType.ProcessBatch(ATS.RChilliParserHelper.CVXtractor.ProcessBatch_In request) {
            return base.Channel.ProcessBatch(request);
        }
        
        public ATS.RChilliParserHelper.CVXtractor.ProcessBatchResponse ProcessBatch(ATS.RChilliParserHelper.CVXtractor.ProcessBatch ProcessBatch1) {
            ATS.RChilliParserHelper.CVXtractor.ProcessBatch_In inValue = new ATS.RChilliParserHelper.CVXtractor.ProcessBatch_In();
            inValue.ProcessBatch = ProcessBatch1;
            ATS.RChilliParserHelper.CVXtractor.ProcessBatch_Out retVal = ((ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType)(this)).ProcessBatch(inValue);
            return retVal.ProcessBatchResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATS.RChilliParserHelper.CVXtractor.InstallLists_Out ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType.InstallLists(ATS.RChilliParserHelper.CVXtractor.InstallLists_In request) {
            return base.Channel.InstallLists(request);
        }
        
        public ATS.RChilliParserHelper.CVXtractor.InstallListsResponse InstallLists(ATS.RChilliParserHelper.CVXtractor.InstallLists InstallLists1) {
            ATS.RChilliParserHelper.CVXtractor.InstallLists_In inValue = new ATS.RChilliParserHelper.CVXtractor.InstallLists_In();
            inValue.InstallLists = InstallLists1;
            ATS.RChilliParserHelper.CVXtractor.InstallLists_Out retVal = ((ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType)(this)).InstallLists(inValue);
            return retVal.InstallListsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATS.RChilliParserHelper.CVXtractor.RetrieveLists_Out ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType.RetrieveLists(ATS.RChilliParserHelper.CVXtractor.RetrieveLists_In request) {
            return base.Channel.RetrieveLists(request);
        }
        
        public ATS.RChilliParserHelper.CVXtractor.RetrieveListsResponse RetrieveLists(ATS.RChilliParserHelper.CVXtractor.RetrieveLists RetrieveLists1) {
            ATS.RChilliParserHelper.CVXtractor.RetrieveLists_In inValue = new ATS.RChilliParserHelper.CVXtractor.RetrieveLists_In();
            inValue.RetrieveLists = RetrieveLists1;
            ATS.RChilliParserHelper.CVXtractor.RetrieveLists_Out retVal = ((ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType)(this)).RetrieveLists(inValue);
            return retVal.RetrieveListsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATS.RChilliParserHelper.CVXtractor.CreateAccount_Out ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType.CreateAccount(ATS.RChilliParserHelper.CVXtractor.CreateAccount_In request) {
            return base.Channel.CreateAccount(request);
        }
        
        public ATS.RChilliParserHelper.CVXtractor.CreateAccountResponse CreateAccount(ATS.RChilliParserHelper.CVXtractor.CreateAccount CreateAccount1) {
            ATS.RChilliParserHelper.CVXtractor.CreateAccount_In inValue = new ATS.RChilliParserHelper.CVXtractor.CreateAccount_In();
            inValue.CreateAccount = CreateAccount1;
            ATS.RChilliParserHelper.CVXtractor.CreateAccount_Out retVal = ((ATS.RChilliParserHelper.CVXtractor.CVXtractor_PortType)(this)).CreateAccount(inValue);
            return retVal.CreateAccountResponse;
        }
    }
}
